import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        <ClerkProvider>
          <GoogleOneTap />
          <main className="flex-grow">{children}</main>
          <footer className="text-center text-sm text-gray-500 pb-4">
            © {new Date().getFullYear()} AI Course Creator. All rights reserved.
          </footer>
        </ClerkProvider>
      </body>
    </html>
  );
}
